# Generated by Django 5.2.6 on 2026-01-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='artist_audio/'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
