# Generated by Django 5.2.6 on 2026-01-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_date_remove_event_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingrequest',
            unique_together={('event', 'artist')},
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
