# Generated by Django 5.2.6 on 2026-01-12 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_artistprofile_user_alter_organiserprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organiserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
