# Generated by Django 4.2.30 on 2026-09-01 09:50

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_bookingrequest_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
    ]
