# Generated by Django 4.2.30 on 2026-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organiserprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="organiserprofile",
            name="social_link",
            field=models.URLField(blank=True),
        ),
    ]
